import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SeesionWrapper from "@/components/client/wrappers/sessionWrapper"
import HandleView from "@/components/client/support-chat/handleView"

export const dynamic = "force-dynamic"

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
})

export const metadata: Metadata = {
	title: "SzablonyDiscord",
	description: "Generated by create next app",
	icons: {
		icon: "/logo.svg",
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<html lang="pl">
				<body className={inter.className}>
					<SeesionWrapper>
						{" "}
						<HandleView />
						{children}
					</SeesionWrapper>
				</body>
			</html>
		</>
	)
}
