import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SeesionWrapper from "@/components/client/wrappers/sessionWrapper"
import HandleView from "@/components/client/chat/handleView"
import ShoppingCartPopup from "@/components/client/shoppingCart/ShoppingCartPopup"
import { Toaster } from "sonner"
import { CircleAlert, CircleCheckBig } from "lucide-react"
import SettingsFetcher from "@/components/client/settings/SettingsFetcher"
import { User } from "@/components/interfaces/common"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/authOptions"
import { prisma } from "@repo/db"

export const dynamic = "force-dynamic"

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
})

export const metadata: Metadata = {
	title: "SzablonyDiscord",
	description: "Generated by create next app",
	icons: {
		icon: "/logo.svg",
	},
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await getServerSession(authOptions)
	let user: User | null = null

	if (session) {
		user = await prisma.user.findUnique({
			where: { userId: session?.user.id },
			include: {
				api: true,
				settings: true,
				limits: true,
				notification: {
					take: 4,
					orderBy: {
						createdAt: "desc",
					},
				},
				builder: {
					take: 5,
					include: {
						builderProcess: {
							include: {
								stages: {
									include: {
										channel: {
											include: {
												channel: true,
											},
										},
										category: {
											include: {
												category: true,
											},
										},
										role: {
											include: {
												role: true,
											},
										},
									},
								},
							},
						},
					},
				},
			},
		})
	}

	return (
		<>
			<html lang="pl">
				<body className={inter.className}>
					<Toaster
						expand={false}
						toastOptions={{
							className: "",
							style: {
								backgroundColor: "#1c1c1c",
								border: "1px solid #262626",
								color: "#ffffff",
								display: "flex",
								alignItems: "center",
								gap: "12px",
								padding: "12px",
							},
						}}
						icons={{
							success: <CircleCheckBig size="24" className="bg-darknes-primary-color text-primary-color p-1 rounded-lg flex-shrink-0" />,
							error: <CircleAlert size="24" className="bg-darknes-error-color text-error-color p-1 rounded-lg flex-shrink-0" />,
						}}
					/>
					<SeesionWrapper initialUser={user}>
						{" "}
						<SettingsFetcher />
						<HandleView />
						<ShoppingCartPopup />
						{children}
					</SeesionWrapper>
				</body>
			</html>
		</>
	)
}
