import BuilderWrapper from "@/components/client/builder/builderWrapper"
import type { Metadata } from "next"
import React from "react"
import { prisma } from "@repo/db"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

interface LayoutParams {
	params: { id: string }
	children: React.ReactNode
}

export default async function RootLayout({ params, children }: LayoutParams) {
	const { id } = await params

	const data = await prisma.generateStatus.findUnique({
		where: { sessionId: id },
		include: { roles: true, channel: true, category: true },
	})
	return (
		<>
			<BuilderWrapper id={id} data={data}>
				{children}
			</BuilderWrapper>
		</>
	)
}
