-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('NEW', 'PAID', 'COMPLETED', 'CANCELED', 'REFUND_PENDING', 'REFUNDED', 'PARTIALLY_REFUNDED');

-- CreateEnum
CREATE TYPE "DeliveryMethod" AS ENUM ('EMAIL', 'AUTOMATIC');

-- CreateEnum
CREATE TYPE "StatusOffer" AS ENUM ('ACTIVE', 'INACTIVE', 'SOLD');

-- CreateEnum
CREATE TYPE "RolesPossible" AS ENUM ('ADMIN', 'USER', 'SUPPORT', 'PREMIUM');

-- CreateEnum
CREATE TYPE "ProtectionType" AS ENUM ('BASIC', 'PREMIUM', 'ADVANCED', 'OTHER');

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('SUCCESS', 'ERROR', 'WARNING');

-- CreateEnum
CREATE TYPE "BuilderProcessStatus" AS ENUM ('WAITING', 'IN_PROGRESS', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "BuilderStageType" AS ENUM ('ANALYSIS', 'AUTHENTICATION', 'CONFIGURE_SERVER', 'ROLES_CREATE', 'CHANNELS_CREATE', 'CATEGORIES_CREATE');

-- CreateEnum
CREATE TYPE "TemplateCategory" AS ENUM ('ALL', 'ROLEPLAY', 'THEMATIC', 'ENGLISH', 'SOCIAL', 'NSFW', 'GROUPS_OF_PEOPLE', 'GUILDS', 'MEMES', 'SCAM', 'ANIME', 'GTA', 'DEV', 'MINECRAFT', 'GAMING', 'ADVERTISING', 'AI');
